spring.application.name=trustly-provider-service
server.port=8083

# MongoDB Connection for our audit logs
spring.data.mongodb.uri=mongodb://localhost:27017/trustly_audit_logs

# --- DEPLOYMENT CONFIGURATION ---
# The address for the downstream mock-trustly-service.
# For local dev, this is localhost. For EC2, we'll change it to the public IP.
mock.trustly.url=http://localhost:8084